### ISSUE TITLE
Loading model behind a proxy

### ISSUE THREAD

**Issue by robinderat** [fcakyon/yolov5-pip#3]
I want to use yolov5 from behind a proxy limiting access to the internet. I made sure the model the model weights are available locally, however when running `yolov5 = YOLOv5("resources/models/v1.pt")` the program still tries to reach github.

The problem seems to be located in [attempt_download](https://github.com/fcakyon/yolov5-pip/blob/66a22df5f118a1607945f03393a35ba1bd8e4810/yolov5/utils/google_utils.py#L19) in google_utils.py.

Here the program tries to retrieve the assets from github and checks whether a download is required afterwards.
```
response = requests.get('https://api.github.com/repos/ultralytics/yolov5/releases/latest').json()  # github api
assets = [x['name'] for x in response['assets']]  # release assets, i.e. ['yolov5s.pt', 'yolov5m.pt', ...]
redundant = False  # second download option

if file in assets and not os.path.isfile(weights):
   try:  # GitHub
```
Am I correct in believing that this assets lookup can be avoided when the weights are already available? I.e., wrap the code in a `if not os.path.isfile(weights)` statement.

**Comment by fcakyon** [comment]
@robinderat good catch, will fix it today.

**Comment by glenn-jocher** [comment]
@fcakyon @robinderat this was fixed in https://github.com/ultralytics/yolov5/pull/1894 in January, I would use the latest google_utils.py:
https://github.com/ultralytics/yolov5/blob/master/utils/google_utils.py

The fix was implemented by PR

**Comment by fcakyon** [comment]
@robinderat it is fixed in version 4.0.6

Just `pip install -U yolov5`

**Comment by timstokman** [comment]
@fcakyon Version 4.0.6 hasn't been published yet (https://pypi.org/project/yolov5/#history). Could you publish? I'm having this issue as well.

**Comment by fcakyon** [comment]
@timstokman thanks for reminding. Now you can install over pip.

**Comment by timstokman** [comment]
@fcakyon It looks like the issue still occurs in version 4.0.6. The version of google_utils that you have checked in doesn't seem to be up-to-date with the yolov5 version:

https://github.com/fcakyon/yolov5-pip/blob/main/yolov5/utils/google_utils.py vs https://github.com/ultralytics/yolov5/blob/master/utils/google_utils.py

It can be worked around, but the workaround is not particulary pleasant if you want to have this code function in environments w/o networking available.

**Comment by fcakyon** [comment]
@timstokman @orphan2020 thanks for reporting. should be fixed with [v4.0.7](https://pypi.org/project/yolov5/4.0.7/#history). try `pip install -U yolov5`
